@startuml

  |Аналітик|
  start
  :Натискає кнопку \n«Add question»;
  |Система|
  :Пропонує форму \n«New question»;
  |Аналітик|
  :Заповнює поля \n«Question type»;
  |Система|
  :Пропонує форму \nпитання згідно \nобраному типу;
  |Аналітик|
  :Заповнює поле «Question», \n«Answer» та по бажанню \nполе «Description»;
  stop

@enduml