@startuml

    |Аналітик|
    start
    :Натискає кнопку \n«Create a poll»;
    |Система|
    :Пропонує форму \n«New poll»;
    |Аналітик|
    :Заповнює поле «Poll title» \nта додає принаймні \nодне питання;
    :Завершує редагування \nанкети натисканням \nкнопки «Done»;
    |Система|
    :Опрацьовує анкету;
    |Аналітик|
    stop

@enduml
