@startuml

  |Користувач|
  start
  :Натискає кнопку \n«Sign in»;
  |Система|
  :Пропонує форму \n«Authentication»;
  |Користувач|
  :Заповнює поля \n«E-mail», «Password»;
  |Користувач|
  :Натискає кнопку \n«Login»;
  |Система|
  :Авторизує \nкористувача;
  
  stop

@enduml