@startuml

  |Експерт|
  start
  :Натискає кнопку \n«Begin the survey»;
  |Система|
  :Пропонує форму \n«Poll for experts»;
  |Експерт|
  :Заповнює поля \nз відповідями;
  |Експерт|
  :Натискає кнопку \n«Send»;
  |Система|
  :Зберігає відповіді;
  
  stop

@enduml