@startuml

    |Користувач|
    start
    :Натискає кнопку \n«Create profile»;
    |Система|
    :Пропонує форму \n«Create new user»;
    |Користувач|
    :Заповнює поля: \nлогін, пароль, \nпрізвище, ім’я, e-mail;
    :Підтверджує \nправильність \nвведених даних;
    |Система|
    :Перевіряє введені \nдані;
    :Надає доступ до \nствореного акаунту;
    |Користувач|
    stop

@enduml
