-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 14:14:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BeatType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BeatType` (
  `name` VARCHAR(45) NOT NULL,
  `installer` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceChan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServiceChan` (
  `id` INT NOT NULL,
  `next` VARCHAR(45) NULL,
  `ServiceChan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ServiceChan_ServiceChan1_idx` (`ServiceChan_id` ASC) VISIBLE,
  CONSTRAINT `fk_ServiceChan_ServiceChan1`
    FOREIGN KEY (`ServiceChan_id`)
    REFERENCES `mydb`.`ServiceChan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stream` (
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `etc` VARCHAR(245) NULL,
  `ServiceChan_id` INT NOT NULL,
  INDEX `fk_Stream_ServiceChan1_idx` (`ServiceChan_id` ASC) VISIBLE,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_Stream_ServiceChan1`
    FOREIGN KEY (`ServiceChan_id`)
    REFERENCES `mydb`.`ServiceChan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Beat` (
  `id Guid` INT NOT NULL,
  `interval` INT NULL,
  `BeatType_name` VARCHAR(45) NOT NULL,
  `Stream_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id Guid`),
  INDEX `fk_Beat_BeatType1_idx` (`BeatType_name` ASC) VISIBLE,
  INDEX `fk_Beat_Stream1_idx` (`Stream_name` ASC) VISIBLE,
  CONSTRAINT `fk_Beat_BeatType1`
    FOREIGN KEY (`BeatType_name`)
    REFERENCES `mydb`.`BeatType` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beat_Stream1`
    FOREIGN KEY (`Stream_name`)
    REFERENCES `mydb`.`Stream` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Source` (
  `url` VARCHAR(245) GENERATED ALWAYS AS () VIRTUAL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `apikey` TEXT NOT NULL,
  `Beat_id Guid` INT NOT NULL,
  PRIMARY KEY (`url`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_Source_Beat_idx` (`Beat_id Guid` ASC) VISIBLE,
  CONSTRAINT `fk_Source_Beat`
    FOREIGN KEY (`Beat_id Guid`)
    REFERENCES `mydb`.`Beat` (`id Guid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `status` INT NULL,
  `Beat_id Guid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Beat1_idx` (`Beat_id Guid` ASC) VISIBLE,
  CONSTRAINT `fk_User_Beat1`
    FOREIGN KEY (`Beat_id Guid`)
    REFERENCES `mydb`.`Beat` (`id Guid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceNode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServiceNode` (
  `url` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(245) NOT NULL,
  `OpenApi` VARCHAR(245) NOT NULL,
  `ServiceChan_id` INT NOT NULL,
  INDEX `fk_ServiceNode_ServiceChan1_idx` (`ServiceChan_id` ASC) VISIBLE,
  CONSTRAINT `fk_ServiceNode_ServiceChan1`
    FOREIGN KEY (`ServiceChan_id`)
    REFERENCES `mydb`.`ServiceChan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`BeatType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`BeatType` (`name`, `installer`) VALUES ('MCAS', '-');
INSERT INTO `mydb`.`BeatType` (`name`, `installer`) VALUES ('MCAS2', '-');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ServiceChan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ServiceChan` (`id`, `next`, `ServiceChan_id`) VALUES (0, ' 1', DEFAULT);
INSERT INTO `mydb`.`ServiceChan` (`id`, `next`, `ServiceChan_id`) VALUES (1, '2', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Beat`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Beat` (`id Guid`, `interval`, `BeatType_name`, `Stream_name`) VALUES (0, 10, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`Beat` (`id Guid`, `interval`, `BeatType_name`, `Stream_name`) VALUES (1, 3, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`Beat` (`id Guid`, `interval`, `BeatType_name`, `Stream_name`) VALUES (2, 4, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`Beat` (`id Guid`, `interval`, `BeatType_name`, `Stream_name`) VALUES (3, 1, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Source`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Source` (`url`, `password`, `username`, `apikey`, `Beat_id Guid`) VALUES ('http:/MCAS.ua', '00000', 'MCAS', '-', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`User` (`id`, `password`, `email`, `username`, `status`, `Beat_id Guid`) VALUES (0, '12345', '1234@gmial.com', 'Albert', 0, DEFAULT);
INSERT INTO `mydb`.`User` (`id`, `password`, `email`, `username`, `status`, `Beat_id Guid`) VALUES (1, '000000', 'oleh@mail.ua', 'Oleg11', 0, DEFAULT);
INSERT INTO `mydb`.`User` (`id`, `password`, `email`, `username`, `status`, `Beat_id Guid`) VALUES (2, 'qwerty', 'qwerty@gmail.com', 'Qwerty', 0, DEFAULT);
INSERT INTO `mydb`.`User` (`id`, `password`, `email`, `username`, `status`, `Beat_id Guid`) VALUES (3, 'onetwo', 'nazar@gmail.com', 'Nazar11', 0, DEFAULT);
INSERT INTO `mydb`.`User` (`id`, `password`, `email`, `username`, `status`, `Beat_id Guid`) VALUES (4, 'novatrr', 'nova@gmail.com', 'Nova41', 0, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ServiceNode`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ServiceNode` (`url`, `name`, `description`, `OpenApi`, `ServiceChan_id`) VALUES ('', 'first', 'not given', DEFAULT, DEFAULT);

COMMIT;
